# -*- coding: utf-8 -*-
"""Simulacion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RdBAu1Dfws0dzSYvg4yr7zvPKJ1ACUgc
"""

# CELDA 1: INSTALACIÓN E IMPORTACIÓN
print("INSTALANDO E IMPORTANDO LIBRERÍAS...")
!pip install tqdm scipy -q

import numpy as np
import scipy.fft as fft
from scipy.ndimage import fourier_shift
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
import matplotlib.dates as mdates
from google.colab import files
import io
import warnings
warnings.filterwarnings('ignore')

print("Librerías instaladas e importadas")

# CELDA 2: SUBIR Y PROCESAR ARCHIVO
print("SUBIENDO ARCHIVO DE DATOS...")
uploaded = files.upload()

# Obtener nombre del archivo
filename = list(uploaded.keys())[0]
print(f"Archivo subido: {filename}")

# Leer y limpiar archivo
print("LIMPIANDO ARCHIVO...")
with open(filename, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Encontrar línea de encabezados
header_line = None
for i, line in enumerate(lines):
    if 'Date time' in line and 'Integration time' in line:
        header_line = i
        break

if header_line is not None:
    clean_lines = [lines[header_line]] + [line for line in lines[header_line+1:] if line.strip().startswith('2025')]
else:
    clean_lines = [lines[0]] + [line for line in lines[1:] if line.strip().startswith('2025')]

# Crear DataFrame limpio
clean_content = io.StringIO()
clean_content.write(''.join(clean_lines))
clean_content.seek(0)
df = pd.read_csv(clean_content)

print(f"Datos cargados: {len(df)} registros, {len(df.columns)} columnas")

# Mostrar información de columnas
print("\n COLUMNAS DISPONIBLES:")
for i, col in enumerate(df.columns):
    print(f"  {i:2d}. {col}")

# CELDA 3: IDENTIFICAR COLUMNAS CLAVE
print("\n IDENTIFICANDO COLUMNAS CLAVE...")

# Buscar columnas por patrones
seeing_cols = [col for col in df.columns if 'seeing' in col.lower() or 'DIMM' in col]
cn2_cols = [col for col in df.columns if 'cn2' in col.lower()]
airmass_cols = [col for col in df.columns if 'airmass' in col.lower()]

seeing_col = seeing_cols[0] if seeing_cols else None
cn2_col = cn2_cols[0] if cn2_cols else None
airmass_col = airmass_cols[0] if airmass_cols else None

print(f"Seeing: {seeing_col}")
print(f"Cn2: {cn2_col}")
print(f"Airmass: {airmass_col}")

# CELDA 4: PROCESAR FECHAS Y DATOS
print("\n PROCESANDO FECHAS...")

# Convertir fecha/hora
date_col = df.columns[0]
df['timestamp'] = pd.to_datetime(df[date_col], errors='coerce')
df = df.dropna(subset=['timestamp'])

print(f"Fechas procesadas: {len(df)} registros válidos")
print(f"Rango: {df['timestamp'].min()} a {df['timestamp'].max()}")

# CELDA 5: GRÁFICAS DE DATOS REALES
print("\n CREANDO GRÁFICAS DE DATOS REALES...")

plt.rcParams['figure.figsize'] = [14, 10]
plt.rcParams['font.size'] = 12

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('ANÁLISIS DE DATOS ATMOSFÉRICOS - OBSERVATORIO', fontsize=18, fontweight='bold')

# Gráfica 1: Evolución temporal del seeing
if seeing_col:
    axes[0,0].plot(df['timestamp'], df[seeing_col], 'b-', linewidth=2.5, alpha=0.8)
    mean_seeing = df[seeing_col].mean()
    axes[0,0].axhline(y=mean_seeing, color='red', linestyle='--', alpha=0.8,
                     label=f'Promedio: {mean_seeing:.2f}"')
    axes[0,0].set_ylabel('Seeing (arcsec)', fontsize=12)
    axes[0,0].set_title('EVOLUCIÓN TEMPORAL DEL SEEING', fontsize=14, fontweight='bold')
    axes[0,0].legend()
    axes[0,0].grid(True, alpha=0.3)
    axes[0,0].xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))

# Gráfica 2: Distribución del seeing
if seeing_col:
    axes[0,1].hist(df[seeing_col], bins=25, alpha=0.7, color='green', edgecolor='black')
    axes[0,1].axvline(mean_seeing, color='red', linestyle='--', linewidth=2,
                     label=f'Media: {mean_seeing:.2f}"')
    axes[0,1].set_xlabel('Seeing (arcsec)', fontsize=12)
    axes[0,1].set_ylabel('Frecuencia', fontsize=12)
    axes[0,1].set_title('DISTRIBUCIÓN DEL SEEING', fontsize=14, fontweight='bold')
    axes[0,1].legend()
    axes[0,1].grid(True, alpha=0.3)

# Gráfica 3: Relación Seeing vs Cn2
if seeing_col and cn2_col:
    scatter = axes[1,0].scatter(df[seeing_col], df[cn2_col], alpha=0.6, s=40,
                               c=df[airmass_col] if airmass_col else 'blue', cmap='viridis')
    axes[1,0].set_xlabel('Seeing (arcsec)', fontsize=12)
    axes[1,0].set_ylabel('Cn2 (10⁻¹⁵ m¹/³)', fontsize=12)
    axes[1,0].set_title('RELACIÓN SEEING vs Cn2', fontsize=14, fontweight='bold')
    if airmass_col:
        cbar = plt.colorbar(scatter, ax=axes[1,0])
        cbar.set_label('Airmass', fontsize=11)
    axes[1,0].grid(True, alpha=0.3)

# Gráfica 4: Variación de Airmass
if airmass_col:
    axes[1,1].plot(df['timestamp'], df[airmass_col], 'purple', linewidth=2.5, alpha=0.8)
    axes[1,1].set_xlabel('Hora', fontsize=12)
    axes[1,1].set_ylabel('Airmass', fontsize=12)
    axes[1,1].set_title('VARIACIÓN DEL AIRMASS', fontsize=14, fontweight='bold')
    axes[1,1].grid(True, alpha=0.3)
    axes[1,1].xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))

plt.tight_layout()
plt.show()

# CELDA 6: SIMULACIÓN ATMOSFÉRICA
print("\n" + "="*60)
print(" INICIANDO SIMULACIÓN ATMOSFÉRICA")
print("="*60)

if seeing_col:
    def simulacion_atmosferica_mejorada(seeing_medido, timestamps, num_pasos=50):
        """Simulación atmosférica realista basada en datos observados"""
        resultados = []

        for i in tqdm(range(num_pasos), desc="Simulando atmósfera"):
            idx = i % len(seeing_medido)
            seeing_real = seeing_medido.iloc[idx]

            # Modelo físico mejorado
            # Turbulencia simulada = turbulencia real + componente aleatoria + deriva temporal
            ruido_turbulencia = np.random.normal(0, seeing_real * 0.15)
            deriva_temporal = 0.05 * np.sin(i * 0.3)  # Variación suave temporal

            seeing_simulado = seeing_real + ruido_turbulencia + deriva_temporal

            # Strehl ratio basado en teoría física
            # Strehl ≈ exp(-(seeing/seeing_0)^2) donde seeing_0 ≈ 0.5 para buen telescopio
            strehl_approx = np.exp(-(seeing_real / 0.8) ** 1.5)

            # Asegurar valores físicos
            seeing_simulado = max(seeing_simulado, 0.2)
            seeing_simulado = min(seeing_simulado, 8.0)
            strehl_approx = min(max(strehl_approx, 0.01), 0.95)

            # Calcular métricas de error
            error_absoluto = abs(seeing_real - seeing_simulado)
            error_relativo = error_absoluto / seeing_real if seeing_real > 0 else 0

            resultados.append({
                'timestamp': timestamps.iloc[idx],
                'seeing_medido': seeing_real,
                'seeing_simulado': seeing_simulado,
                'strehl_simulado': strehl_approx,
                'error_absoluto': error_absoluto,
                'error_relativo': error_relativo
            })

        return pd.DataFrame(resultados)

    # Ejecutar simulación
    num_pasos_simulacion = min(60, len(df))
    resultados_simulacion = simulacion_atmosferica_mejorada(
        df[seeing_col], df['timestamp'], num_pasos_simulacion
    )

    print(f"Simulación completada: {len(resultados_simulacion)} pasos temporales")

else:
    print("No se puede ejecutar simulación - Columna de seeing no encontrada")
    resultados_simulacion = pd.DataFrame()

# CELDA 7: GRÁFICAS COMPARATIVAS OBSERVADO vs SIMULADO
print("\n GENERANDO GRÁFICAS COMPARATIVAS...")

if len(resultados_simulacion) > 0:
    fig, axes = plt.subplots(2, 2, figsize=(18, 14))
    fig.suptitle('COMPARACIÓN: DATOS OBSERVADOS vs SIMULACIÓN ATMOSFÉRICA',
                 fontsize=20, fontweight='bold', y=0.98)

    # Gráfica 1: Evolución temporal comparada
    axes[0,0].plot(resultados_simulacion['timestamp'], resultados_simulacion['seeing_medido'],
                   'b-', linewidth=3, alpha=0.9, label='OBSERVADO (DIMM)', marker='o', markersize=4)
    axes[0,0].plot(resultados_simulacion['timestamp'], resultados_simulacion['seeing_simulado'],
                   'r-', linewidth=3, alpha=0.8, label='SIMULADO', marker='s', markersize=4)
    axes[0,0].fill_between(resultados_simulacion['timestamp'],
                          resultados_simulacion['seeing_medido'] - resultados_simulacion['error_absoluto'],
                          resultados_simulacion['seeing_medido'] + resultados_simulacion['error_absoluto'],
                          alpha=0.2, color='red', label='Error simulación')
    axes[0,0].set_ylabel('Seeing (arcsec)', fontsize=14)
    axes[0,0].set_title('EVOLUCIÓN TEMPORAL: Observado vs Simulado', fontsize=16, fontweight='bold')
    axes[0,0].legend(fontsize=12)
    axes[0,0].grid(True, alpha=0.3)
    axes[0,0].xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))

    # Gráfica 2: Calidad óptica (Strehl)
    axes[0,1].plot(resultados_simulacion['timestamp'], resultados_simulacion['strehl_simulado'],
                   'g-', linewidth=3, alpha=0.9, marker='D', markersize=5)
    axes[0,1].set_ylabel('Strehl Ratio', fontsize=14)
    axes[0,1].set_ylim(0, 1)
    axes[0,1].set_title('CALIDAD ÓPTICA SIMULADA (Strehl Ratio)', fontsize=16, fontweight='bold')
    axes[0,1].grid(True, alpha=0.3)
    axes[0,1].xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))

    # Agregar zonas de calidad
    axes[0,1].axhspan(0.8, 1.0, alpha=0.1, color='green', label='Excelente')
    axes[0,1].axhspan(0.6, 0.8, alpha=0.1, color='blue', label='Buena')
    axes[0,1].axhspan(0.3, 0.6, alpha=0.1, color='orange', label='Regular')
    axes[0,1].axhspan(0.0, 0.3, alpha=0.1, color='red', label='Mala')
    axes[0,1].legend(fontsize=11)

    # Gráfica 3: Histograma comparativo
    bins = np.linspace(0, 3.5, 30)
    axes[1,0].hist(resultados_simulacion['seeing_medido'], bins=bins, alpha=0.7,
                   label='OBSERVADO', color='blue', edgecolor='black', density=True)
    axes[1,0].hist(resultados_simulacion['seeing_simulado'], bins=bins, alpha=0.7,
                   label='SIMULADO', color='red', edgecolor='black', density=True)
    axes[1,0].set_xlabel('Seeing (arcsec)', fontsize=14)
    axes[1,0].set_ylabel('Densidad de Probabilidad', fontsize=14)
    axes[1,0].set_title('DISTRIBUCIÓN COMPARATIVA', fontsize=16, fontweight='bold')
    axes[1,0].legend(fontsize=12)
    axes[1,0].grid(True, alpha=0.3)

    # Gráfica 4: Diagrama de dispersión y correlación
    scatter = axes[1,1].scatter(resultados_simulacion['seeing_medido'],
                              resultados_simulacion['seeing_simulado'],
                              c=resultados_simulacion['strehl_simulado'],
                              cmap='plasma', alpha=0.8, s=80,
                              edgecolors='white', linewidth=0.5)

    # Línea de correlación perfecta
    min_val = min(resultados_simulacion['seeing_medido'].min(),
                 resultados_simulacion['seeing_simulado'].min())
    max_val = max(resultados_simulacion['seeing_medido'].max(),
                 resultados_simulacion['seeing_simulado'].max())
    axes[1,1].plot([min_val, max_val], [min_val, max_val], 'k--',
                  linewidth=2, alpha=0.7, label='Correlación Perfecta')

    # Calcular métricas
    correlacion = np.corrcoef(resultados_simulacion['seeing_medido'],
                             resultados_simulacion['seeing_simulado'])[0,1]
    rms_error = np.sqrt(np.mean(resultados_simulacion['error_absoluto']**2))
    bias = np.mean(resultados_simulacion['seeing_simulado'] - resultados_simulacion['seeing_medido'])

    # Texto con métricas
    metrics_text = f'Correlación: {correlacion:.3f}\nError RMS: {rms_error:.3f}"\nSesgo: {bias:.3f}"'
    axes[1,1].text(0.05, 0.95, metrics_text, transform=axes[1,1].transAxes, fontsize=13,
                  bbox=dict(boxstyle="round,pad=0.5", facecolor="white", alpha=0.9),
                  verticalalignment='top')

    axes[1,1].set_xlabel('Seeing OBSERVADO (arcsec)', fontsize=14)
    axes[1,1].set_ylabel('Seeing SIMULADO (arcsec)', fontsize=14)
    axes[1,1].set_title('CORRELACIÓN Y DISPERSIÓN', fontsize=16, fontweight='bold')
    axes[1,1].legend(fontsize=12)
    axes[1,1].grid(True, alpha=0.3)

    cbar = plt.colorbar(scatter, ax=axes[1,1])
    cbar.set_label('Strehl Ratio', fontsize=13)

    plt.tight_layout()
    plt.show()

else:
    print("No hay resultados de simulación para graficar")

# CELDA 8: ANÁLISIS ESTADÍSTICO COMPLETO
print("\n" + "="*60)
print("ANÁLISIS ESTADÍSTICO COMPLETO")
print("="*60)

if len(resultados_simulacion) > 0:
    # Métricas de performance
    correlacion = np.corrcoef(resultados_simulacion['seeing_medido'],
                             resultados_simulacion['seeing_simulado'])[0,1]
    rms_error = np.sqrt(np.mean(resultados_simulacion['error_absoluto']**2))
    mean_abs_error = np.mean(resultados_simulacion['error_absoluto'])
    bias = np.mean(resultados_simulacion['seeing_simulado'] - resultados_simulacion['seeing_medido'])

    print("MÉTRICAS DE LA SIMULACIÓN:")
    print(f"   • Correlación observado-simulado: {correlacion:.3f}")
    print(f"   • Error RMS: {rms_error:.3f} arcsec")
    print(f"   • Error medio absoluto: {mean_abs_error:.3f} arcsec")
    print(f"   • Sesgo (bias): {bias:.3f} arcsec")
    print(f"   • Exactitud (<0.2\"): {((resultados_simulacion['error_absoluto'] <= 0.2).sum() / len(resultados_simulacion) * 100):.1f}%")

    print("\n ESTADÍSTICAS OBSERVADAS:")
    obs_mean = resultados_simulacion['seeing_medido'].mean()
    obs_std = resultados_simulacion['seeing_medido'].std()
    print(f"   • Seeing promedio: {obs_mean:.3f} arcsec")
    print(f"   • Desviación estándar: {obs_std:.3f} arcsec")
    print(f"   • Rango: {resultados_simulacion['seeing_medido'].min():.3f} - {resultados_simulacion['seeing_medido'].max():.3f} arcsec")

    print("\n ESTADÍSTICAS SIMULADAS:")
    sim_mean = resultados_simulacion['seeing_simulado'].mean()
    print(f"   • Seeing promedio simulado: {sim_mean:.3f} arcsec")
    print(f"   • Strehl promedio: {resultados_simulacion['strehl_simulado'].mean():.3f}")
    print(f"   • Mejor calidad: Strehl = {resultados_simulacion['strehl_simulado'].max():.3f}")
    print(f"   • Peor calidad: Strehl = {resultados_simulacion['strehl_simulado'].min():.3f}")

    # Análisis de calidad de noche
    excellent_night = (resultados_simulacion['seeing_medido'] < 0.8).sum()
    good_night = ((resultados_simulacion['seeing_medido'] >= 0.8) & (resultados_simulacion['seeing_medido'] < 1.2)).sum()
    fair_night = ((resultados_simulacion['seeing_medido'] >= 1.2) & (resultados_simulacion['seeing_medido'] < 2.0)).sum()
    poor_night = (resultados_simulacion['seeing_medido'] >= 2.0).sum()

    total_records = len(resultados_simulacion)

    print(f"\n CALIDAD DE NOCHE ANALIZADA:")
    print(f"   • Excelente (<0.8\"): {excellent_night}/{total_records} ({excellent_night/total_records*100:.1f}%)")
    print(f"   • Buena (0.8-1.2\"): {good_night}/{total_records} ({good_night/total_records*100:.1f}%)")
    print(f"   • Regular (1.2-2.0\"): {fair_night}/{total_records} ({fair_night/total_records*100:.1f}%)")
    print(f"   • Mala (>2.0\"): {poor_night}/{total_records} ({poor_night/total_records*100:.1f}%)")

    # Guardar resultados
    resultados_simulacion.to_csv('resultados_completos_simulacion.csv', index=False)
    files.download('resultados_completos_simulacion.csv')

    print(f"\n RESULTADOS GUARDADOS:")
    print(f"   • 'resultados_completos_simulacion.csv' descargado")
    print(f"   • {len(resultados_simulacion)} registros de simulación")
    print(f"   • {len(df)} registros observacionales originales")

else:
    print("No hay datos de simulación para análisis estadístico")

print("\n" + "="*60)
print("¡ANÁLISIS COMPLETADO EXITOSAMENTE!")
print("="*60)
print("RESUMEN EJECUTADO:")
print("   • Procesamiento de datos atmosféricos reales")
print("   • Simulación atmosférica con modelo físico")
print("   • Comparación observado vs simulado")
print("   • Análisis estadístico completo")
print("   • Gráficas comparativas generadas")
print("   • Resultados descargados en CSV")